# Importing required libraries

- **Bamboolib** is a free library that gives pandas a GUI interface. It makes it very easy to get graphs and manipulate the rows and columns of the data frame

- **pandas** is the most popular data frame library in python. it just makes it easy to store and manipulate data

In [1]:
import bamboolib as bam
import pandas as pd

# Getting the data from the google sheet

- the following block of code just reads the data from the google sheets where the survey data is going to.(https://docs.google.com/spreadsheets/d/12ojjnk25qPNqnhrhIPjBmfLIDbD3aoynV7emSwuaK7Y/edit#gid=324197163)

In [2]:
gsheetid = "12ojjnk25qPNqnhrhIPjBmfLIDbD3aoynV7emSwuaK7Y"
sheet_name = "data"
gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)
df = pd.read_csv(gsheet_url)

### Dropping Unncessary Columns

In [3]:
df = df.drop(columns=['Timestamp']) #The Timestamp column really is not needed in our study

# Looking at relationships between the data

- bamboolib has a function patterns() which shows the predictive powet score of all the variables. Think of it as a better version of coerrelation. We will still use a coerrelation matrix later on though

In [ ]:
bam.patterns(df)

## Observing the relationship between 'in person?' and 'more_distracted_at_home?'

In [12]:
bam.plot(df, 'in person?', 'more_distracted_at_home?')

TabSection(children=(BrowserCheck(), HBox(children=(Tab(closable=False, title='plot', _dom_classes=('bamboolib…

In [13]:
df['in person?_label'] = df['in person?'].factorize(sort=False, na_sentinel=-1)[0]
df['major_label'] = df['major'].factorize(sort=False, na_sentinel=-1)[0]
df['labs?_label'] = df['labs?'].factorize(sort=False, na_sentinel=-1)[0]
df['easy_internet?_label'] = df['easy_internet?'].factorize(sort=False, na_sentinel=-1)[0]
df['more_distracted_at_home?_label'] = df['more_distracted_at_home?'].factorize(sort=False, na_sentinel=-1)[0]

In [14]:
bam.correlations(df)

TabSection(children=(BrowserCheck(), HBox(children=(Tab(closable=False, title='correlations', _dom_classes=('b…

In [15]:
bam.plot(df, 'in person?', 'more_distracted_at_home?')

TabSection(children=(BrowserCheck(), HBox(children=(Tab(closable=False, title='plot', _dom_classes=('bamboolib…

In [16]:
bam.plot(df, 'in person?', 'labs?')

TabSection(children=(BrowserCheck(), HBox(children=(Tab(closable=False, title='plot', _dom_classes=('bamboolib…

,in person?,major,labs?,num_of_units,easy_internet?,max_screentime,more_distracted_at_home?,commute_time_mins,personality_rating,in person?_label,major_label,labs?_label,easy_internet?_label,more_distracted_at_home?_label
0,No,Math,Yes,14.00,No,130,Yes,34,2,0,0,0,0,0
1,Yes,Humanities/Social Sciences,No,12.00,Yes,40,Yes,35,4,1,1,1,1,0
2,No,Science,Yes,18.00,Yes,180,No,20,1,0,2,0,1,1
3,Yes,Engineering/CS/DS,Yes,14.00,Yes,240,Yes,41,3,1,3,0,1,0
4,Yes,Engineering/CS/DS,No,20.00,Yes,240,Yes,25,2,1,3,1,1,0
5,Yes,Math,No,16.00,Yes,20,Yes,15,3,1,0,1,1,0
6,Yes,Humanities/Social Sciences,No,21.50,No,250,Yes,30,2,1,1,1,0,0
7,Yes,Science,Yes,22.00,Yes,600,Yes,20,2,1,2,0,1,0
8,No,Engineering/CS/DS,Yes,12.50,Yes,480,No,40,3,0,3,0,1,1
9,Yes,Engineering/CS/DS,Yes,16.00,Yes,120,No,20,2,1,3,0,1,1
10,No,Engineering/CS/DS,Yes,20.00,Yes,960,No,120,2,0,3,0,1,1
11,No,Engineering/CS/DS,Yes,21.50,Yes,960,No,180,1,0,3,0,1,1
12,No,Engineering/CS/DS,Yes,20.00,Yes,120,No,20,3,0,3,0,1,1
13,Yes,Engineering/CS/DS,No,9.67,Yes,600,No,60,2,1,3,1,1,1
14,No,Engineering/CS/DS,Yes,14.00,Yes,10,Yes,90,3,0,3,0,1,0
15,No,Science,Yes,12.00,Yes,1080,No,90,2,0,2,0,1,1
16,No,Humanities/Social Sciences,Yes,9.00,Yes,3,No,10,3,0,1,0,1,1
17,No,Humanities/Social Sciences,No,12.00,Yes,240,Yes,15,3,0,1,1,1,0
18,No,Engineering/CS/DS,Yes,12.00,Yes,120,Yes,15,4,0,3,0,1,0
19,No,Humanities/Social Sciences,No,14.00,Yes,60,Yes,30,3,0,1,1,1,0
20,No,Science,Yes,18.00,Yes,700,No,960,4,0,2,0,1,1
21,No,Science,Yes,12.00,Yes,180,No,240,4,0,2,0,1,1
22,Yes,Math,No,12.00,Yes,60,Yes,20,2,1,0,1,1,0
23,Yes,Engineering/CS/DS,Yes,15.00,Yes,300,Yes,20,3,1,3,0,1,0
24,No,Science,Yes,12.00,Yes,1080,No,40,2,0,2,0,1,1
25,No,Science,Yes,14.00,Yes,120,No,10,1,0,2,0,1,1
26,No,Engineering/CS/DS,Yes,13.00,Yes,90,Yes,10,3,0,3,0,1,0
27,No,Humanities/Social Sciences,No,12.00,Yes,500,No,20,1,0,1,1,1,1
28,No,Science,Yes,14.00,Yes,120,No,30,5,0,2,0,1,1
29,No,Engineering/CS/DS,No,16.00,Yes,300,No,43,2,0,3,1,1,1
30,No,Engineering/CS/DS,Yes,10.50,Yes,600,Yes,20,2,0,3,0,1,0
31,No,Humanities/Social Sciences,No,12.00,Yes,180,Yes,15,1,0,1,1,1,0
32,No,Humanities/Social Sciences,Yes,11.00,Yes,360,No,15,2,0,1,0,1,1
33,No,Science,Yes,0.00,Yes,30,Yes,60,3,0,2,0,1,0
34,No,Humanities/Social Sciences,No,20.50,Yes,180,No,15,3,0,1,1,1,1
35,Yes,Engineering/CS/DS,Yes,4.00,Yes,60,Yes,30,3,1,3,0,1,0
36,No,Engineering/CS/DS,No,6.00,Yes,120,Yes,20,3,0,3,1,1,0
37,Yes,Humanities/Social Sciences,No,13.00,Yes,400,Yes,25,3,1,1,1,1,0
38,Yes,Humanities/Social Sciences,Yes,8.00,Yes,60,Yes,20,3,1,1,0,1,0
39,No,Science,Yes,7.00,Yes,120,No,45,4,0,2,0,1,1
40,No,Humanities/Social Sciences,Yes,8.00,Yes,480,Yes,25,1,0,1,0,1,0
41,Yes,Science,Yes,6.00,Yes,60,No,20,3,1,2,0,1,1
42,No,Science,Yes,14.00,Yes,120,No,10,1,0,2,0,1,1
43,No,Engineering/CS/DS,Yes,20.00,Yes,120,Yes,30,2,0,3,0,1,0
44,No,Humanities/Social Sciences,No,12.00,Yes,120,Yes,20,4,0,1,1,1,0
45,No,Science,Yes,14.00,Yes,210,No,15,1,0,2,0,1,1
46,No,Science,Yes,14.00,Yes,120,No,10,1,0,2,0,1,1
47,No,Science,Yes,6.00,Yes,600,Yes,75,3,0,2,0,1,0
48,No,Humanities/Social Sciences,No,12.00,Yes,120,Yes,20,1,0,1,1,1,0